# @package _group_

name: caffe/DenseNet_121
layers:
  - {name: conv1_abs, num: 500}
  - {name: concat_2_1, num: 500}
  - {name: concat_2_2, num: 500}
  - {name: concat_2_3, num: 500}
  - {name: concat_2_4, num: 500}
  - {name: concat_2_5, num: 500}
  - {name: concat_2_6, num: 500}
  - {name: concat_3_1, num: 500}
  - {name: concat_3_2, num: 500}
  - {name: concat_3_3, num: 500}
  - {name: concat_3_4, num: 500}
  - {name: concat_3_5, num: 500}
  - {name: concat_3_6, num: 500}
  - {name: concat_3_7, num: 500}
  - {name: concat_3_8, num: 500}
  - {name: concat_3_9, num: 500}
  - {name: concat_3_10, num: 500}
  - {name: concat_3_11, num: 500}
  - {name: concat_3_12, num: 500}
  - {name: concat_4_1, num: 500}
  - {name: concat_4_2, num: 500}
  - {name: concat_4_3, num: 500}
  - {name: concat_4_4, num: 500}
  - {name: concat_4_5, num: 500}
  - {name: concat_4_6, num: 500}
  - {name: concat_4_7, num: 500}
  - {name: concat_4_8, num: 500}
  - {name: concat_4_9, num: 500}
  - {name: concat_4_10, num: 500}
  - {name: concat_4_11, num: 500}
  - {name: concat_4_12, num: 500}
  - {name: concat_4_13, num: 500}
  - {name: concat_4_14, num: 500}
  - {name: concat_4_15, num: 500}
  - {name: concat_4_16, num: 500}
  - {name: concat_4_17, num: 500}
  - {name: concat_4_18, num: 500}
  - {name: concat_4_19, num: 500}
  - {name: concat_4_20, num: 500}
  - {name: concat_4_21, num: 500}
  - {name: concat_4_22, num: 500}
  - {name: concat_4_23, num: 500}
  - {name: concat_4_24, num: 500}
  - {name: concat_5_1, num: 500}
  - {name: concat_5_2, num: 500}
  - {name: concat_5_3, num: 500}
  - {name: concat_5_4, num: 500}
  - {name: concat_5_5, num: 500}
  - {name: concat_5_6, num: 500}
  - {name: concat_5_7, num: 500}
  - {name: concat_5_8, num: 500}
  - {name: concat_5_9, num: 500}
  - {name: concat_5_10, num: 500}
  - {name: concat_5_11, num: 500}
  - {name: concat_5_12, num: 500}
  - {name: concat_5_13, num: 500}
  - {name: concat_5_14, num: 500}
  - {name: concat_5_15, num: 500}
  - {name: concat_5_16, num: 500}
  - {name: fc6, num: 500}
