# @package _group_

name: tensorflow/resnet_v2_50
layers:
  - {name: resnet_v2_50:conv1_abs, num: 500}
  - {name: resnet_v2_50:block1:unit_1:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block1:unit_2:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block1:unit_3:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block2:unit_1:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block2:unit_2:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block2:unit_3:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block2:unit_4:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block3:unit_1:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block3:unit_2:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block3:unit_3:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block3:unit_4:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block3:unit_5:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block3:unit_6:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block4:unit_1:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block4:unit_2:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:block4:unit_3:bottleneck_v2, num: 500}
  - {name: resnet_v2_50:logits, num: 500}
