# DNN feature decoding

encoder:
  name: deeprecon_fmriprep_hcp_rois_pyfastl2lir_alpha100_500units
  path: ./data/feature_encoders/ImageNetTraining/${encoder.name}/${encoder.features.name}
  parameters:
    alpha: 100

  fmri:
    name: ImageNetTraining_fmriprep_volume_native
    subjects:
      #- name: sub-01
      #  paths:
      #    - ./data/fmri/Deeprecon/sub-01_${encoder.fmri.name}_hcpvc.h5
      #- name: sub-02
      #  paths:
      #    - ./data/fmri/Deeprecon/sub-02_${encoder.fmri.name}_hcpvc.h5
      - name: sub-03
        paths:
          - ./data/fmri/Deeprecon/sub-03_${encoder.fmri.name}_hcpvc.h5
    rois:
      - {name: V1,        select: hcp180_V1 = 1}
      - {name: V2,        select: hcp180_V2 = 1}
      - {name: V3,        select: hcp180_V3 = 1}
      - {name: V4,        select: hcp180_V4 = 1}
      - {name: VentralVC, select: hcp180_VentralVC = 1}
    label_key: stimulus_name

  features:
    name: caffe/VGG19
    paths:
      - ./data/features/ImageNetTraining/${encoder.features.name}
    layers:
      #- {name: conv1_1, num: 500}
      - {name: conv1_2, num: 500}
      #- {name: conv2_1, num: 500}
      - {name: conv2_2, num: 500}
      #- {name: conv3_1, num: 500}
      #- {name: conv3_2, num: 500}
      #- {name: conv3_3, num: 500}
      - {name: conv3_4, num: 500}
      #- {name: conv4_1, num: 500}
      #- {name: conv4_2, num: 500}
      #- {name: conv4_3, num: 500}
      - {name: conv4_4, num: 500}
      #- {name: conv5_1, num: 500}
      #- {name: conv5_2, num: 500}
      #- {name: conv5_3, num: 500}
      - {name: conv5_4, num: 500}
      - {name: fc6,     num: 500}
      - {name: fc7,     num: 500}
      - {name: fc8,     num: 500}

encoded_fmri:
  name: deeprecon_fmriprep_hcp_rois_pyfastl2lir_alpha100_500units
  path: ./data/encoded_fmri/ImageNetTest/${encoded_fmri.name}/${encoded_fmri.features.name}
  parameters:
    average_sample: true

  encoder:
    name: deeprecon_fmriprep_pyfastl2lir_alpha100_allunits
    path: ./data/feature_encoders/ImageNetTraining/${encoder.name}/${encoder.features.name}

  fmri:
    name: ImageNetTest_fmriprep_volume_native
    subjects:
      #- name: sub-01
      #  paths:
      #    - ./data/fmri/Deeprecon/sub-01_${encoded_fmri.fmri.name}_vc_hcpvc.h5
      #- name: sub-02
      #  paths:
      #    - ./data/fmri/Deeprecon/sub-02_${encoded_fmri.fmri.name}_vc_hcpvc.h5
      - name: sub-03
        paths:
          - ./data/fmri/Deeprecon/sub-03_${encoded_fmri.fmri.name}_vc_hcpvc.h5
    rois:
      - {name: V1,        select: hcp180_V1 = 1}
      - {name: V2,        select: hcp180_V2 = 1}
      - {name: V3,        select: hcp180_V3 = 1}
      - {name: V4,        select: hcp180_V4 = 1}
      - {name: VentralVC, select: hcp180_VentralVC = 1}
    label_key: stimulus_name
    exclude_labels:

  features:
    name: caffe/VGG19
    paths:
      - ./data/features/ImageNetTest/${encoded_fmri.features.name}
    layers:
      #- {name: conv1_1, num: 500}
      - {name: conv1_2, num: 500}
      #- {name: conv2_1, num: 500}
      - {name: conv2_2, num: 500}
      #- {name: conv3_1, num: 500}
      #- {name: conv3_2, num: 500}
      #- {name: conv3_3, num: 500}
      - {name: conv3_4, num: 500}
      #- {name: conv4_1, num: 500}
      #- {name: conv4_2, num: 500}
      #- {name: conv4_3, num: 500}
      - {name: conv4_4, num: 500}
      #- {name: conv5_1, num: 500}
      #- {name: conv5_2, num: 500}
      #- {name: conv5_3, num: 500}
      - {name: conv5_4, num: 500}
      - {name: fc6,     num: 500}
      - {name: fc7,     num: 500}
      - {name: fc8,     num: 500}
